#ifndef ROBOT_ERRORS_H
#define ROBOT_ERRORS_H
/* Frozen numeric values from src/common/contract.json. */
typedef enum {
    ROBOT_OK = 0,
    ROBOT_INVALID_ARGUMENT = 1001,
    ROBOT_UNIT_MISMATCH = 1002,
    ROBOT_JOINT_ORDER_MISMATCH = 1003,
    ROBOT_MODEL_NOT_CONFIGURED = 1004,
    ROBOT_JOINT_LIMIT_EXCEEDED = 1005,
    ROBOT_INVALID_TIME = 1006,
    ROBOT_FRAME_MISMATCH = 1007,
    ROBOT_NOT_IMPLEMENTED = 1008,
    ROBOT_IK_UNREACHABLE = 2001,
    ROBOT_IK_NO_CONVERGENCE = 2002,
    ROBOT_KINEMATIC_SINGULARITY = 2003,
    ROBOT_PLANNING_FAILED = 3001,
    ROBOT_TRAJECTORY_LIMIT_EXCEEDED = 3002,
    ROBOT_COLLISION_DETECTED = 3003,
    ROBOT_INVALID_CONTROL_STATE = 4001,
    ROBOT_FEEDBACK_TIMEOUT = 4002,
    ROBOT_TRACKING_ERROR_EXCEEDED = 4003,
    ROBOT_COMMAND_LIMIT_EXCEEDED = 4004,
    ROBOT_IO_FAILURE = 5001,
    ROBOT_INTERNAL_ERROR = 9000
} robot_error_code;
#endif
